/**
 * C2 Pack Schema — TypeScript types
 * Source of truth: Arbor Spec/21 Contracts/C2 Pack Schema.md
 * Mirror of: contracts/pack.schema.json
 *
 * Generated by an architect session. Do NOT hand-edit.
 * Import in source via: import type { Pack, … } from '../../contracts/pack';
 */

export interface Pack {
  schema_version: 1;
  node_id: string;
  overview: Overview;
  segments: Segment[];
  templates: QuestionTemplate[];
  /** Bank of ≥10 items. Runtime draws exactly 10 per attempt, mapped across outcome_refs. */
  diagnostic: DiagnosticItem[];
  /** Maximum 800 characters. */
  summary_for_context: string;
  addenda?: Addendum[];
}

export interface Overview {
  summary_for_learner: string;
  outline: string[];
  /** node_id values of prerequisite children assumed completed. */
  assumed_children: string[];
}

export interface Segment {
  /** Kebab-case segment identifier, unique within the pack. */
  id: string;
  intent: string;
  /** KaTeX-renderable question. */
  question: string;
  /**
   * Classifier paths.
   * Invariant: at least one path has is_misconception === true.
   */
  expected_paths: ExpectedPath[];
  /**
   * Hint sequence in ascending support order.
   * Invariant: last step must have level === 'tell'.
   * Minimum 4 steps: probe → nudge → near-answer → tell.
   */
  hint_ladder: HintStep[];
  /** Scripted resolution delivered after correct answer or after 'tell'. */
  resolution: string;
  quick_checks: QuickCheck[];
}

export interface ExpectedPath {
  label: string;
  classifier_hint: string;
  response: string;
  is_misconception: boolean;
}

export interface HintStep {
  level: 'probe' | 'nudge' | 'near-answer' | 'tell';
  text: string;
}

export interface QuickCheck {
  question: string;
  expected_answer: string;
}

export interface QuestionTemplate {
  /** Kebab-case template identifier, unique within the pack. */
  id: string;
  /** KaTeX-renderable question stem; may contain {param_name} placeholders. */
  stem: string;
  /** Named parameter ranges for re-rolling. Absent for non-parameterised templates. */
  parameters?: Record<string, ParamSpec>;
  /** Sympy-parseable expression; may reference parameter names. */
  answer_expr: string;
  /** Guidance for the strong model when judging free-form answers. */
  marking_notes: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface ParamSpec {
  type: 'integer' | 'float';
  min?: number;
  max?: number;
  exclude_zero?: boolean;
}

export interface DiagnosticItem {
  /** Kebab-case item identifier, unique within the pack. */
  id: string;
  question: string;
  expected_answer: string;
  is_parameterized?: boolean;
  /** Only present when is_parameterized === true. */
  param_seed?: number;
  /** Sympy expression; only present when is_parameterized === true. */
  answer_expr?: string;
  /** Outcome identifiers (from node.outcomes_json) this item tests. */
  outcome_refs: string[];
}

export interface Addendum {
  /** Sequential addendum ID: add-001, add-002, … */
  id: string;
  /** ISO 8601 date. */
  date: string;
  reason: string;
  content: string;
}
